# syntax=docker/dockerfile:1

FROM golang:1.22-alpine as build

WORKDIR /src

COPY <<EOF /src/main.go
package main

func main(){
    println("Full Cycle Rocks!!!")
}
EOF

RUN go build -ldflags "-s -w" -o /bin/rocks ./main.go


FROM scratch
COPY --from=build /bin/rocks /bin/rocks
CMD [ "/bin/rocks" ]
